name: Test action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Change Code
      run: |
        echo -e "\n$(date)" >> test/Gettysburg_Address.txt
    
    - name: Verify action syntax
      # The action should not publish any real changes, but should succeed.
      uses: './'
      with:
        git_token_holder: 'liziwl'
        git_token: '${{ secrets.BIT_TOKEN }}'
        commit_user: 'liziwl'
        commit_email: 'leezisy@gmail.com'
        push_dir: 'test/'
        repository_url: 'bitbucket.org/liziwl/push-action-demo.git'
        # keep_history: false # default false
        # branch: master # default master
        # commit_message: 'Psuh by action bot' # default "Deploy COMMIT_SHA"
